<?php

namespace Xekvern\Core\Server\Entity\Types;

use pocketmine\entity\Living;
use pocketmine\entity\Location;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\nbt\tag\IntTag;

abstract class BaseEntity extends Living
{

    const STACK = 'stack';

    private int $stack = 1;

    public function __construct(Location $location, ?CompoundTag $nbt)
    {
        parent::__construct($location, $nbt);
    }

    protected function initEntity(CompoundTag $nbt): void
    {
        parent::initEntity($nbt);
        $this->stack = $nbt->getInt(self::STACK, 1);
        $nbt->setInt(self::STACK, $this->stack);
    }

    public function saveNBT(): CompoundTag
    {
        $nbt = parent::saveNBT();
        $nbt->setInt(self::STACK, $this->stack);
        return $nbt;
    }

    public function getSaveId(): string
    {
        return (new \ReflectionClass($this))->getShortName();
    }

    public function canSaveWithChunk(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
}
